version: "3"
services:
  docker-notebook:
    build: 
    # build from Dockerfile
        context: .
        dockerfile: Dockerfile
    environment:
     - JUPYTER_TOKEN=datacamp
    ports:
     - "5000:5000"
    volumes:
     - ./:/home/jovyan/work
    container_name: docker-notebook
